# Specify docker image
image: debian:stretch

# Define variable to disable SSL verification of GIT
variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - tarballs
  - trigger

build-tarballs:
  stage: tarballs
  only:
    - /^1.*$/
  script:
    - mkdir ../fusiondirectory-$(cut -d '-' -f1 <<< $CI_COMMIT_REF_NAME)
    - cp -a ./* ../fusiondirectory-$(cut -d '-' -f1 <<< $CI_COMMIT_REF_NAME)
    - mv ../fusiondirectory-$(cut -d '-' -f1 <<< $CI_COMMIT_REF_NAME) ./
  artifacts:
    name: fusiondirectory-$(cut -d '-' -f1 <<< $CI_COMMIT_REF_NAME)
    paths:
    - ./fusiondirectory-$(cut -d '-' -f1 <<< $CI_COMMIT_REF_NAME)
    expire_in: 1h

build-release:
  stage: tarballs
  only:
    - tags
  script:
    - mkdir "../fusiondirectory-$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"')"
    - cp -a ./* "../fusiondirectory-$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"')"
    - mv "../fusiondirectory-$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"')" ./       
  artifacts:
    name: fusiondirectory-"$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"')"
    paths:
    - ./fusiondirectory-"$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"')"

trigger-plugins:
  variables:
    GROUP: $GROUP
    BRANCH_CORE: $CI_COMMIT_REF_NAME
    BRANCH_PLUGIN: $CI_COMMIT_REF_NAME
    BRANCH_BUILD_DEBIAN_STRETCH: $BRANCH_BUILD_DEBIAN_STRETCH
    BRANCH_BUILD_DEBIAN_BUSTER: $BRANCH_BUILD_DEBIAN_BUSTER
    BRANCH_BUILD_CENTOS_7: $BRANCH_BUILD_CENTOS_7
  stage: trigger
  only:
    - master
  trigger:
    project: fusiondirectory/fd-plugins
    branch: $CI_COMMIT_REF_NAME
